import React, { useState } from 'react';
import { Info } from 'lucide-react';

interface GlossaryTooltipProps {
  term: string;
  definition?: string;
  formula?: string;
  children?: React.ReactNode;
}

export const GLOSSARY: Record<string, { definition: string; formula?: string }> = {
  Fidelity: {
    definition: "Statistical overlap between the expected reference quantum state and the observed reconstructed state at Bob's node.",
    formula: "F = |⟨ψ_exp|ψ_obs⟩|² ∈ [0, 1]",
  },
  "Distribution Deviation": {
    definition: "Total Variation Distance (TVD) quantifying the divergence between expected projective detector counts and actual observed shots.",
    formula: "TVD = ½ ∑ |P_exp(i) - P_obs(i)|",
  },
  "Total Variation Distance (TVD)": {
    definition: "Total Variation Distance (TVD) quantifying the divergence between expected projective detector counts and actual observed shots.",
    formula: "TVD = ½ ∑ |P_exp(i) - P_obs(i)|",
  },
  "Bhattacharyya Distance": {
    definition: "Information-theoretic metric measuring the overlap of two statistical probability distributions.",
    formula: "D_B = -ln( ∑ √(P_exp · P_obs) )",
  },
  "Bell State (|Φ⁺⟩)": {
    definition: "Maximally entangled two-qubit quantum state generated by applying a Hadamard gate followed by a CNOT gate.",
    formula: "|Φ⁺⟩ = 1/√2 (|00⟩ + |11⟩)",
  },
  "Pauli Correction": {
    definition: "Classical feed-forward unitary operations applied to Bob's qubit based on Alice's 2-bit Bell measurement outcome.",
    formula: "U = Z^(m₁) · X^(m₂)",
  },
  "Replay Nonce": {
    definition: "Cryptographic single-use token tied to quantum session entropy. Once consumed, any identical session ID is instantly blocked.",
  },
  "Simulated Quantum State": {
    definition: "Deterministic mathematical model representing state vectors and projective sampling. Designed to be replaced by real QPU or Qiskit backends.",
  },
};

export const GlossaryTooltip: React.FC<GlossaryTooltipProps> = ({
  term,
  definition,
  formula,
  children,
}) => {
  const [isOpen, setIsOpen] = useState(false);

  const activeDef = definition || GLOSSARY[term]?.definition || "Quantum-inspired security parameter";
  const activeFormula = formula || GLOSSARY[term]?.formula;

  return (
    <span 
      className="relative inline-flex items-center gap-1 group cursor-help text-slate-300"
      onMouseEnter={() => setIsOpen(true)}
      onMouseLeave={() => setIsOpen(false)}
      onClick={() => setIsOpen(!isOpen)}
    >
      <span className="border-b border-dotted border-cyan-500/50 hover:text-cyan-300 transition-colors">
        {children || term}
      </span>
      <Info className="w-3.5 h-3.5 text-cyan-400/70 inline-block shrink-0" />

      {isOpen && (
        <div className="absolute z-50 bottom-full left-1/2 -translate-x-1/2 mb-2 w-72 p-3 bg-slate-900/95 border border-cyan-500/40 rounded-lg shadow-2xl backdrop-blur-md text-xs text-slate-200 pointer-events-none transition-all">
          <div className="font-semibold text-cyan-400 font-mono flex items-center justify-between pb-1 mb-1 border-b border-slate-800">
            <span>{term}</span>
            <span className="text-[10px] text-slate-400 uppercase tracking-widest font-sans">Q-Glossary</span>
          </div>
          <p className="leading-relaxed text-slate-300">{activeDef}</p>
          {activeFormula && (
            <div className="mt-2 bg-slate-950/80 p-1.5 rounded border border-cyan-900/40 font-mono text-[11px] text-cyan-300 text-center">
              {activeFormula}
            </div>
          )}
          <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-transparent border-t-slate-900" />
        </div>
      )}
    </span>
  );
};
